fragment ImageFragment on FileFieldInterface {
	id
	width
	height
	alt
	basename
	format
	mimeType
	size
	title
	url
	responsiveImage(imgixParams: { auto: format }, sizes: "(max-width: 46.24em) 50vw, 25vw") {
		width
		height
		alt
		aspectRatio
		base64
		bgColor
		sizes
		src
		srcSet
		webpSrcSet
		title
	}
}
