fragment PostFragment on PostRecord {
	id
	title
	slug
	image {
		...ImageFragment
	}
	content(markdown: false)
	structuredContent {
		blocks
		links
		value
	}
	background {
		hex
	}
	createdAt
	updatedAt
	author {
		id
		name
	}
}
