query Post($slug: String, $locale: SiteLocale) {
	post(locale: $locale, filter: { slug: { eq: $slug } }) {
		...PostFragment
	}
}

query AllPosts($locale: SiteLocale, $first: IntType = 500, $skip: IntType = 0) {
	allPosts(locale: $locale, first: $first, skip: $skip) {
		...PostFragment
	}
	_allPostsMeta {
		count
	}
}

fragment PostFragment on PostRecord {
	image {
		...ImageFragment
	}
	intro
	slug
	title
	content {
		blocks {
			__typename
		}
		value
		links
	}
	author {
		name
	}
	_updatedAt
}

fragment PostLightFragment on PostRecord {
	image {
		...ImageFragment
	}
	intro
	slug
	title
	author {
		name
	}
	_updatedAt
}
